export default {
  basicRock: {
    name: "Basic Rock",
    tempo: 96,
    subdivision: 8,
    bars: 1,
    beatsPerBar: 4,
    beat: 4,
    notes: {
      hiHat: [
        {timing: "1.1.1", vol: 2},
        {timing: "1.1.2", vol: 2},
        {timing: "1.2.1", vol: 2},
        {timing: "1.2.2", vol: 2},
        {timing: "1.3.1", vol: 2},
        {timing: "1.3.2", vol: 2},
        {timing: "1.4.1", vol: 2},
        {timing: "1.4.2", vol: 2},
      ],
      rackTom: [],
      snare: [{timing: "1.2.1", vol: 2}, {timing: "1.4.1", vol: 2}],
      floorTom: [],
      kick: [{timing: "1.1.1", vol: 2}, {timing: "1.3.1", vol: 2}],
    }
  },
  dance: {
    name: "Dance",
    tempo: 120,
    subdivision: 16,
    bars: 1,
    beatsPerBar: 4,
    beat: 4,
    notes: {
      hiHat: [
        {timing: "1.1.1", vol: 1},
        {timing: "1.1.2", vol: 1},
        {timing: "1.1.3", vol: 2},
        {timing: "1.1.4", vol: 1},
        {timing: "1.2.1", vol: 1},
        {timing: "1.2.2", vol: 1},
        {timing: "1.2.3", vol: 2},
        {timing: "1.2.4", vol: 1},
        {timing: "1.3.1", vol: 1},
        {timing: "1.3.2", vol: 1},
        {timing: "1.3.3", vol: 2},
        {timing: "1.3.4", vol: 1},
        {timing: "1.4.1", vol: 1},
        {timing: "1.4.2", vol: 1},
        {timing: "1.4.3", vol: 2},
        {timing: "1.4.4", vol: 1},
      ],
      rackTom: [],
      snare: [{timing: "1.2.1", vol: 2}, {timing: "1.4.1", vol: 2}],
      floorTom: [],
      kick: [
        {timing: "1.1.1", vol: 2},
        {timing: "1.2.1", vol: 2},
        {timing: "1.3.1", vol: 2},
        {timing: "1.4.1", vol: 2},
      ],
    }
  },
  train: {
    name: "Country Train",
    tempo: 90,
    subdivision: 16,
    bars: 1,
    beatsPerBar: 4,
    beat: 4,
    notes: {
      hiHat: [ ],
      rackTom: [],
      snare: [
        {timing: "1.1.1", vol: 1},
        {timing: "1.1.2", vol: 1},
        {timing: "1.1.3", vol: 2},
        {timing: "1.1.4", vol: 1},
        {timing: "1.2.1", vol: 1},
        {timing: "1.2.2", vol: 1},
        {timing: "1.2.3", vol: 2},
        {timing: "1.2.4", vol: 1},
        {timing: "1.3.1", vol: 1},
        {timing: "1.3.2", vol: 1},
        {timing: "1.3.3", vol: 2},
        {timing: "1.3.4", vol: 1},
        {timing: "1.4.1", vol: 1},
        {timing: "1.4.2", vol: 1},
        {timing: "1.4.3", vol: 2},
        {timing: "1.4.4", vol: 2},
      ],
      floorTom: [],
      kick: [
        {timing: "1.1.1", vol: 2},
        {timing: "1.2.1", vol: 2},
        {timing: "1.3.1", vol: 2},
        {timing: "1.4.1", vol: 2},
      ],
    }
  },
  halfTimeShuffle: {
    name: "Half-Time Shuffle (Rosanna - Toto)",
    tempo: 86,
    subdivision: 24,
    bars: 1,
    beatsPerBar: 4,
    beat: 4,
    notes: {
      hiHat: [
        {timing: "1.1.1", vol: 2},
        {timing: "1.1.3", vol: 1},
        {timing: "1.1.4", vol: 2},
        {timing: "1.1.6", vol: 1},
        {timing: "1.2.1", vol: 2},
        {timing: "1.2.3", vol: 1},
        {timing: "1.2.4", vol: 2},
        {timing: "1.2.6", vol: 1},
        {timing: "1.3.1", vol: 2},
        {timing: "1.3.3", vol: 1},
        {timing: "1.3.4", vol: 2},
        {timing: "1.3.6", vol: 1},
        {timing: "1.4.1", vol: 2},
        {timing: "1.4.3", vol: 1},
        {timing: "1.4.4", vol: 2},
        {timing: "1.4.6", vol: 1},
      ],
      rackTom: [],
      snare: [
        {timing: "1.1.2", vol: 1},
        {timing: "1.1.3", vol: 1},
        {timing: "1.1.5", vol: 1},
        {timing: "1.2.1", vol: 2},
        {timing: "1.2.2", vol: 1},
        {timing: "1.2.5", vol: 1},
        {timing: "1.2.6", vol: 1},
        {timing: "1.3.2", vol: 1},
        {timing: "1.3.3", vol: 1},
        {timing: "1.3.5", vol: 1},
        {timing: "1.4.1", vol: 2},
        {timing: "1.4.2", vol: 1},
        {timing: "1.4.5", vol: 1},
        {timing: "1.4.6", vol: 1},
      ],
      floorTom: [],
      kick: [
        {timing: "1.1.1", vol: 2},
        {timing: "1.1.6", vol: 2},
        {timing: "1.2.4", vol: 2},
        {timing: "1.3.3", vol: 2},
        {timing: "1.4.1", vol: 2},
        {timing: "1.4.6", vol: 2},
      ],
    }
  },
  shuffle: {
    name: "Blues Shuffle",
    tempo: 96,
    subdivision: 12,
    bars: 1,
    beatsPerBar: 4,
    beat: 4,
    notes: {
      hiHat: [
        {timing: "1.1.1", vol: 2},
        {timing: "1.2.1", vol: 2},
        {timing: "1.3.1", vol: 2},
        {timing: "1.4.1", vol: 2},
      ],
      rackTom: [],
      snare: [
        {timing: "1.1.1", vol: 1},
        {timing: "1.1.3", vol: 1},
        {timing: "1.2.1", vol: 2},
        {timing: "1.2.3", vol: 1},
        {timing: "1.3.1", vol: 1},
        {timing: "1.3.3", vol: 1},
        {timing: "1.4.1", vol: 2},
        {timing: "1.4.3", vol: 1},
      ],
      floorTom: [],
      kick: [
        {timing: "1.1.1", vol: 2},
        {timing: "1.2.1", vol: 2},
        {timing: "1.3.1", vol: 2},
        {timing: "1.4.1", vol: 2},
      ],
    }
  },
}
